from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setMinimumSize(QtCore.QSize(450, 600))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.volume_up = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up.setGeometry(QtCore.QRect(110, 220, 71, 51))
        self.volume_up.setObjectName("volume_up")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 190, 221, 23))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setTabletTracking(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.volume_up_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_2.setGeometry(QtCore.QRect(170, 390, 71, 51))
        self.volume_up_2.setObjectName("volume_up_2")
        self.volume_up_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_3.setGeometry(QtCore.QRect(230, 220, 71, 51))
        self.volume_up_3.setObjectName("volume_up_3")
        self.volume_up_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_4.setGeometry(QtCore.QRect(110, 280, 71, 51))
        self.volume_up_4.setObjectName("volume_up_4")
        self.volume_up_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_5.setGeometry(QtCore.QRect(170, 220, 71, 51))
        self.volume_up_5.setObjectName("volume_up_5")
        self.volume_up_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_6.setGeometry(QtCore.QRect(230, 280, 71, 51))
        self.volume_up_6.setObjectName("volume_up_6")
        self.volume_up_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_7.setGeometry(QtCore.QRect(240, 350, 51, 71))
        self.volume_up_7.setObjectName("volume_up_7")
        self.volume_up_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_8.setGeometry(QtCore.QRect(240, 410, 51, 71))
        self.volume_up_8.setObjectName("volume_up_8")
        self.volume_up_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_9.setGeometry(QtCore.QRect(120, 350, 51, 71))
        self.volume_up_9.setObjectName("volume_up_9")
        self.volume_up_10 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_10.setGeometry(QtCore.QRect(120, 410, 51, 71))
        self.volume_up_10.setObjectName("volume_up_10")
        self.volume_up_11 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volume_up_11.setGeometry(QtCore.QRect(170, 280, 71, 51))
        self.volume_up_11.setObjectName("volume_up_11")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 81, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TV Remote"))
        self.volume_up.setText(_translate("MainWindow", "1"))
        self.volume_up_2.setText(_translate("MainWindow", "🔇"))
        self.volume_up_3.setText(_translate("MainWindow", "3"))
        self.volume_up_4.setText(_translate("MainWindow", "4"))
        self.volume_up_5.setText(_translate("MainWindow", "2"))
        self.volume_up_6.setText(_translate("MainWindow", "6"))
        self.volume_up_7.setText(_translate("MainWindow", "^"))
        self.volume_up_8.setText(_translate("MainWindow", "⌄"))
        self.volume_up_9.setText(_translate("MainWindow", "+"))
        self.volume_up_10.setText(_translate("MainWindow", "-"))
        self.volume_up_11.setText(_translate("MainWindow", "5"))
        self.pushButton.setText(_translate("MainWindow", "Power"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
